### ISSUE TITLE
Request for the fish dataset.

### ISSUE THREAD

**Issue by Tenglon** [Imageomics/phylo-diffusion#2]
Dear authors, 

Thanks for this inspiring work, we are curious about your research and are trying to use your model to generate samples for our research.

We notice that the dataset used in your research has an expired link:

> Great lakes invasives network project, https://greatlakesinvasives.org/portal/index.php

Would you please let us know how to get access the dataset?

Many thanks!

**Comment by mridulk97** [comment]
Thank you for bringing this to our notice! We will update the link in the paper.
I have updated the README with the link to the dataset used.
